(add-to-list 'load-path "~/.emacs.d")

;; My configs
(load "nebirhos/defuns")
(load "nebirhos/packages")
(load "nebirhos/global")
(load "nebirhos/ido")
(load "nebirhos/ui")
(load "nebirhos/files")
(load "nebirhos/snippets")
(load "nebirhos/navigation")
(load "nebirhos/undo")
(load "nebirhos/speedbar")
(load "nebirhos/magit")
(load "nebirhos/visual-regexp")
(load "nebirhos/bindings")
(load "nebirhos/tab")
(load "nebirhos/spell")

;; My modes
(load "nebirhos/ruby")
(load "nebirhos/rbenv")
(load "nebirhos/rails")
(load "nebirhos/coffee")
(load "nebirhos/sass")
(load "nebirhos/slim")
(load "nebirhos/yaml")
(load "nebirhos/markdown")
(load "nebirhos/javascript")
(load "nebirhos/feature")
(load "nebirhos/jade")
(load "nebirhos/jsx")

(setq sgml-basic-offset 4)
