(add-to-list 'load-path "~/.emacs.d/vendor")

;; My configs
(load "defunkt/defuns")
(load "nebirhos/defuns")
(load "nebirhos/global")
(load "nebirhos/ui")
(load "nebirhos/files")
(load "nebirhos/snippets")
(load "nebirhos/speedbar")
(load "nebirhos/compile")
(load "nebirhos/bindings")
(vendor 'minimap)
(vendor 'ace-jump-mode)
;; (define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
(define-key global-map (kbd "C-.") 'ace-jump-mode)

;; My modes
(load "nebirhos/ruby")
(load "nebirhos/javascript")
(load "nebirhos/java")
(load "nebirhos/php")
(load "nebirhos/cc")
(load "nebirhos/cucumber")
(load "nebirhos/yaml")
(load "nebirhos/css")
(load "nebirhos/slim")
(load "nebirhos/coffee")
(load "nebirhos/sass")
(load "nebirhos/android")
