(add-to-list 'load-path "~/.emacs.d/vendor")

;; My configs
(load "defunkt/defuns")
(load "nebirhos/defuns")
(load "nebirhos/global")
(load "nebirhos/files")
(load "nebirhos/snippets")
(load "nebirhos/bindings")
(load "nebirhos/theme")
(load "nebirhos/emacsclient")
; modes
(load "nebirhos/ruby")
(load "nebirhos/javascript")
(load "nebirhos/yaml")
(load "nebirhos/java")
(load "nebirhos/php")
(load "nebirhos/cc")
(load "nebirhos/cucumber")
(load "nebirhos/css")
(load "nebirhos/android")
(load "nebirhos/markup-langs")
(load "nebirhos/speedbar")